/* daniel-fox.com — "Cinema" motion layer. Edit directly (not generated by build.py).
   Loaded deferred from _src/layouts/base.html on every page.

   Dependency-free, ES5-ish on purpose: this site has no build step and no npm.
   One rAF loop drives every piece of scroll choreography — no per-section
   listeners. Only transform / opacity / filter are animated.

   Everything degrades:
     - prefers-reduced-motion  -> `.rm`: scenes unpin, all content static + visible
     - no WebGL                -> static CSS gradient fallback layer
     - no IntersectionObserver -> everything revealed immediately
     - no JS at all            -> `.js` is never set, so nothing is ever hidden
     - hard failsafe           -> everything forced visible 1.8s after load
*/
(function () {
  'use strict';

  var doc = document.documentElement;
  var body = document.body;
  var reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var fine = window.matchMedia('(hover: hover) and (pointer: fine)').matches;
  if (reduce) { doc.classList.add('rm'); }

  var isHome = body.classList.contains('home');
  var isRead = body.classList.contains('article') || body.classList.contains('blog-index');

  /* Pinned scenes need a viewport tall enough to hold a whole scene at once.
     Phones do not have one, and their collapsing toolbars make 100vh a moving
     target, so below 900px the scenes unpin and behave exactly as they do under
     prefers-reduced-motion. `.static-scenes` is what the stylesheet keys off. */
  var mqSmall = window.matchMedia('(max-width: 900px)');
  function scenesStatic() { return reduce || mqSmall.matches; }
  function syncStatic() {
    var stat = scenesStatic();
    doc.classList.toggle('static-scenes', stat);
    if (!stat) { return; }
    // Drop any inline values the scroll loop wrote before the viewport shrank,
    // so the static rules are not fighting stale opacity/transform.
    var sel = '#s-ceiling .stmt, #ceilMedia .cm, #heroInner, #heroPh, #qPhoto';
    document.querySelectorAll(sel).forEach(function (e) {
      ['opacity', 'transform'].forEach(function (prop) { e.style.removeProperty(prop); });
    });
    document.querySelectorAll('.quote-txt .w').forEach(function (w) { w.classList.add('lit'); });
  }
  syncStatic();
  if (mqSmall.addEventListener) { mqSmall.addEventListener('change', syncStatic); }
  else if (mqSmall.addListener) { mqSmall.addListener(syncStatic); }

  /* ====================================================================
     WebGL smoke — purple, half devicePixel scale, ~60fps
     ==================================================================== */
  (function () {
    var cv = document.getElementById('gl');
    var fb = document.getElementById('glfb');
    if (!cv) { return; }
    function bail() { cv.style.display = 'none'; if (fb) { fb.style.display = 'block'; } }

    var gl;
    try { gl = cv.getContext('webgl', { antialias: false, alpha: false }); } catch (e) { gl = null; }
    if (!gl) { bail(); return; }

    var vs = 'attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}';
    var fs = 'precision mediump float;uniform vec2 r;uniform float t;uniform float s;' +
      'float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.545);}' +
      'float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);' +
      'return mix(mix(h(i),h(i+vec2(1.,0.)),f.x),mix(h(i+vec2(0.,1.)),h(i+vec2(1.,1.)),f.x),f.y);}' +
      'float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*n(p);p*=2.03;a*=.5;}return v;}' +
      'void main(){vec2 uv=gl_FragCoord.xy/r;vec2 q=uv*vec2(r.x/r.y,1.);' +
      'float m1=fbm(q*1.4+vec2(t*.10,-t*.065));' +
      'float m2=fbm(q*2.2+vec2(-t*.075,t*.085)+m1*1.4);' +
      'float band=smoothstep(.32,.85,fbm(q*1.1+vec2(t*.05,0.)+m2));' +
      'vec3 base=vec3(.040,.035,.066);' +
      'vec3 c1=vec3(.42,.34,.57);vec3 c2=vec3(.49,.42,.63);' +
      'float glow1=band*smoothstep(1.15,.15,distance(uv,vec2(.78,.85+.08*sin(t*.3))));' +
      'float glow2=fbm(q*1.7-vec2(t*.06,t*.03))*smoothstep(1.1,.05,distance(uv,vec2(.12,.12)));' +
      'vec3 col=base+c1*glow1*.30*s+c2*glow2*.13*s;' +
      'col+=c1*.035*m2*s;' +
      'gl_FragColor=vec4(col,1.);}';

    function sh(type, src) {
      var o = gl.createShader(type);
      gl.shaderSource(o, src);
      gl.compileShader(o);
      return o;
    }
    var pr = gl.createProgram();
    gl.attachShader(pr, sh(gl.VERTEX_SHADER, vs));
    gl.attachShader(pr, sh(gl.FRAGMENT_SHADER, fs));
    gl.linkProgram(pr);
    if (!gl.getProgramParameter(pr, gl.LINK_STATUS)) { bail(); return; }
    gl.useProgram(pr);

    var buf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);
    var loc = gl.getAttribLocation(pr, 'p');
    gl.enableVertexAttribArray(loc);
    gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);

    var uR = gl.getUniformLocation(pr, 'r');
    var uT = gl.getUniformLocation(pr, 't');
    var uS = gl.getUniformLocation(pr, 's');
    var scale = 0.5;

    function size() {
      cv.width = window.innerWidth * scale;
      cv.height = window.innerHeight * scale;
      gl.viewport(0, 0, cv.width, cv.height);
      gl.uniform2f(uR, cv.width, cv.height);
    }
    size();
    window.addEventListener('resize', size, { passive: true });

    var t0 = performance.now();
    // Long-form reading pages keep the palette but drop most of the turbulence —
    // body copy should never compete with a moving background.
    var ceiling = isRead ? 0.45 : 1;
    window.__auroraIntensity = ceiling;
    window.__auroraCeiling = ceiling;

    function frame(now) {
      gl.uniform1f(uT, (now - t0) / 1000);
      gl.uniform1f(uS, window.__auroraIntensity);
      gl.drawArrays(gl.TRIANGLES, 0, 3);
      // Freeze on a single frame under reduced motion; pause in a background tab.
      if (!reduce && !document.hidden) { requestAnimationFrame(frame); }
    }
    requestAnimationFrame(frame);
    document.addEventListener('visibilitychange', function () {
      if (!document.hidden && !reduce) { requestAnimationFrame(frame); }
    });
  })();

  /* ====================================================================
     Letter-split headings — the signature moment, on every page
     ==================================================================== */
  function splitChars(el, startIndex) {
    var i = startIndex || 0;
    var text = el.textContent.replace(/\s+/g, ' ').trim();
    el.textContent = '';
    text.split(' ').forEach(function (word) {
      // Each word is its own inline-block so lines never break mid-word and the
      // DOM text order (what crawlers and screen readers read) is untouched.
      var w = document.createElement('span');
      w.style.display = 'inline-block';
      w.style.whiteSpace = 'nowrap';
      word.split('').forEach(function (ch) {
        var s = document.createElement('span');
        s.className = 'c';
        s.style.setProperty('--i', i++);
        s.textContent = ch;
        w.appendChild(s);
      });
      el.appendChild(w);
      el.appendChild(document.createTextNode(' '));
    });
    return i;
  }

  (function () {
    var h = document.querySelector('.hero-title') ||
            document.querySelector('.hero h1') ||
            document.querySelector('main h1');
    if (!h) { return; }
    // Headings carrying links or images are left alone — splitting would break them.
    if (h.querySelector('a, img, svg')) { return; }

    var payoff = h.querySelector('.payoff');
    var i = 0;
    if (payoff) {
      // Homepage: lead clause, then the payoff line trailing behind it.
      var lead = '';
      Array.prototype.forEach.call(h.childNodes, function (n) {
        if (n.nodeType === 3) { lead += n.textContent; }
      });
      var pText = payoff.textContent;
      var frag = document.createElement('span');
      frag.textContent = lead;
      i = splitChars(frag, 0);
      payoff.textContent = pText;
      splitChars(payoff, i + 8);
      h.innerHTML = '';
      while (frag.firstChild) { h.appendChild(frag.firstChild); }
      h.appendChild(payoff);
    } else {
      splitChars(h, 0);
    }
    h.classList.add('split');
  })();

  /* Hero block: stagger the rest of the hero content in behind the headline. */
  (function () {
    var hero = document.querySelector('.hero > .container');
    if (!hero || isHome) { return; }
    hero.classList.add('hero-in');
    Array.prototype.forEach.call(hero.children, function (el, n) {
      el.style.setProperty('--i', n);
    });
  })();

  /* ====================================================================
     Intro curtain — homepage, once per browser session
     ==================================================================== */
  function start() { body.classList.add('go'); }
  /* The hero's staged delays are timed to trail the 1.15s curtain. With no
     curtain there is nothing to trail, so `.no-intro` pulls them forward. */
  function startNow() { body.classList.add('no-intro'); start(); }

  (function () {
    var intro = document.getElementById('intro');
    if (!intro) { startNow(); return; }

    var seen = false;
    try { seen = sessionStorage.getItem('df-intro') === '1'; } catch (e) { seen = false; }
    if (reduce || seen) { intro.remove(); startNow(); return; }
    try { sessionStorage.setItem('df-intro', '1'); } catch (e) { /* private mode */ }

    var mark = intro.querySelector('.mark');
    'DANIEL FOX'.split('').forEach(function (ch, n) {
      var s = document.createElement('i');
      s.textContent = ch === ' ' ? ' ' : ch;
      s.style.transitionDelay = (n * 45) + 'ms';
      mark.appendChild(s);
    });
    requestAnimationFrame(function () {
      requestAnimationFrame(function () { intro.classList.add('on'); });
    });
    setTimeout(function () { intro.classList.add('done'); start(); }, 1150);
    setTimeout(function () { if (intro.parentNode) { intro.remove(); } }, 2300);
  })();

  /* ====================================================================
     Mobile nav
     ==================================================================== */
  var navBtn = document.querySelector('.nav-toggle');
  var navEl = document.querySelector('.nav-links');
  if (navBtn && navEl) {
    navBtn.addEventListener('click', function () {
      var open = navEl.classList.toggle('open');
      navBtn.setAttribute('aria-expanded', open ? 'true' : 'false');
    });
  }

  /* ====================================================================
     Scroll choreography — one rAF loop for the whole page
     ==================================================================== */
  var hd = document.querySelector('.site-header');
  var heroSec = document.getElementById('s-hero');
  var heroInner = document.getElementById('heroInner');
  var heroPh = document.getElementById('heroPh');
  var ceilSec = document.getElementById('s-ceiling');
  var stmts = ceilSec ? ceilSec.querySelectorAll('.stmt') : [];
  var clProg = document.getElementById('clProg');
  var cms = document.querySelectorAll('#ceilMedia .cm');
  var quoteSec = document.getElementById('s-quote');
  var qPhoto = document.getElementById('qPhoto');
  var quoteTxt = document.getElementById('quoteTxt');
  var band = document.getElementById('band');
  var bandPh = document.getElementById('bandPh');
  var photoLayers = [].slice.call(document.querySelectorAll('.photo-section .photo-bg'));

  /* Split the pinned quote into words so they can light up with scroll progress. */
  var qWords = [];
  if (quoteTxt) {
    var qt = quoteTxt.textContent.trim();
    quoteTxt.textContent = '';
    qt.split(/\s+/).forEach(function (word) {
      var s = document.createElement('span');
      s.className = 'w';
      s.textContent = word;
      quoteTxt.appendChild(s);
      quoteTxt.appendChild(document.createTextNode(' '));
    });
    qWords = quoteTxt.querySelectorAll('.w');
  }

  /* 0 -> 1 across a pinned scene's scrollable overflow. */
  function prog(el) {
    var r = el.getBoundingClientRect();
    var total = r.height - window.innerHeight;
    if (total <= 0) { return 0; }
    return Math.min(1, Math.max(0, -r.top / total));
  }
  /* 0 entering the viewport bottom, 1 leaving the top. */
  function viewProg(el) {
    var r = el.getBoundingClientRect();
    return Math.min(1, Math.max(0, (window.innerHeight - r.top) / (window.innerHeight + r.height)));
  }

  var lastY = 0;
  var ticking = false;

  function update() {
    ticking = false;
    var y = window.pageYOffset;
    var vh = window.innerHeight;

    if (hd) {
      hd.classList.toggle('scrolled', y > 40);
      hd.classList.toggle('hide',
        y > lastY && y > 240 && !(navEl && navEl.classList.contains('open')));
    }
    lastY = y;
    if (scenesStatic()) { return; }

    /* Smoke swells through the middle of the page and settles at either end. */
    var docH = document.body.scrollHeight - vh;
    if (docH > 0) {
      var ceil = window.__auroraCeiling || 1;
      window.__auroraIntensity = ceil * (1 + Math.sin(Math.min(1, y / docH) * Math.PI) * 0.6);
    }

    /* --- pinned hero --- */
    if (heroSec && heroInner) {
      var hp = prog(heroSec);
      // Hold the hero fully composed for the first 55% of its pin before it
      // starts drifting out (the concept began dissolving it at 35%).
      var out = Math.max(0, (hp - 0.55) / 0.45);
      heroInner.style.transform = 'translateY(' + (-out * 12) + 'vh) scale(' + (1 - out * 0.06) + ')';
      heroInner.style.opacity = 1 - out * 1.1;
      if (heroPh) { heroPh.style.transform = 'translateY(' + (hp * 6) + '%)'; }
    }

    /* --- pinned ceiling scene: statements + media crossfade in lockstep --- */
    if (ceilSec && stmts.length) {
      var cp = prog(ceilSec);
      if (clProg) { clProg.style.height = (cp * 100) + '%'; }
      var n = stmts.length;
      for (var i2 = 0; i2 < n; i2++) {
        var seg = 1 / n;
        var local = (cp - i2 * seg) / seg;
        var op = 0;
        var ty = 30;
        // Fade in over the first 14%, HOLD from 14% to 87%, fade out over the
        // last 13%. The concept held for only 55% of each segment, which read as
        // statements flicking past; this holds for ~73%.
        if (local >= 0 && local <= 1) {
          if (local < 0.14) { op = local / 0.14; ty = 30 * (1 - op); }
          else if (local > 0.87 && i2 < n - 1) { op = 1 - (local - 0.87) / 0.13; ty = -24 * (1 - op); }
          else { op = 1; ty = 0; }
        }
        if (i2 === n - 1 && local > 1) { op = 1; ty = 0; }
        stmts[i2].style.opacity = op;
        stmts[i2].style.transform = 'translateY(calc(-50% + ' + ty + 'px))';
        if (cms[i2]) {
          cms[i2].style.opacity = op;
          cms[i2].style.transform = 'scale(' + (1.06 - 0.06 * op) + ')';
        }
      }
    }

    /* --- homepage full-bleed band: parallax + saturation interpolating in --- */
    if (band && bandPh) {
      var bp = viewProg(band);
      bandPh.style.transform = 'translateY(' + ((bp - 0.5) * 14) + '%)';
      var g = Math.min(1, Math.max(0, 1.6 - bp * 2.6));
      bandPh.style.filter = 'saturate(' + (0.5 + (1 - g) * 0.5) + ') grayscale(' + (g * 0.7) +
        ') contrast(1.06) brightness(.95)';
    }

    /* --- site-wide photo bands: the same treatment on all 62 of them --- */
    for (var i4 = 0; i4 < photoLayers.length; i4++) {
      var layer = photoLayers[i4];
      var sec = layer.parentElement;
      var r = sec.getBoundingClientRect();
      if (r.bottom < -120 || r.top > vh + 120) { continue; }   // skip off-screen work
      var vp = Math.min(1, Math.max(0, (vh - r.top) / (vh + r.height)));
      layer.style.transform = 'translate3d(0,' + ((vp - 0.5) * 12).toFixed(2) + '%,0)';
      var gg = Math.min(1, Math.max(0, 1.6 - vp * 2.6));
      layer.style.filter = 'saturate(' + (0.5 + (1 - gg) * 0.5).toFixed(3) + ') grayscale(' +
        (gg * 0.6).toFixed(3) + ') contrast(1.06) brightness(.95)';
    }

    /* --- pinned quote: photo pulls back, words light up --- */
    if (quoteSec && qWords.length) {
      var qp = prog(quoteSec);
      if (qPhoto) { qPhoto.style.transform = 'scale(' + (1.12 - qp * 0.1) + ')'; }
      // 1.1, not 1.25: the quote finishes lighting at ~91% of the scene rather
      // than 80%, so the last words don't land while there is still scroll left.
      var lit = Math.floor(qp * 1.1 * qWords.length);
      for (var i3 = 0; i3 < qWords.length; i3++) {
        qWords[i3].classList.toggle('lit', i3 < lit);
      }
    }
  }

  function onScroll() {
    if (!ticking) { ticking = true; requestAnimationFrame(update); }
  }
  window.addEventListener('scroll', onScroll, { passive: true });
  window.addEventListener('resize', onScroll, { passive: true });
  update();

  /* ====================================================================
     Reveals — varied by design; plain fade-up is never the only move
     ==================================================================== */
  (function () {
    var VARIANTS = ['rv-v1', 'rv-v2', 'rv-v4', 'rv-v3'];
    var containers = [].slice.call(document.querySelectorAll('.reveal'));
    containers.forEach(function (el, n) {
      el.classList.add(VARIANTS[n % VARIANTS.length]);
      Array.prototype.forEach.call(el.children, function (kid, k) {
        kid.style.setProperty('--i', k);
      });
    });

    var grids = [].slice.call(document.querySelectorAll(
      '.explore-grid, .post-grid, .related-grid, .grid, .steps, .cap-grid, .fit-cols'));
    grids.forEach(function (g) {
      Array.prototype.forEach.call(g.children, function (kid, k) {
        kid.style.setProperty('--i', k);
      });
    });

    var bands = [].slice.call(document.querySelectorAll('.photo-section:not(.photo-hero), .band'));
    var standalone = [].slice.call(document.querySelectorAll('.rv, .rv-l, .rv-r, .rv-wipe, .rv-zoom'));
    var all = containers.concat(grids, bands, standalone);
    if (!all.length) { return; }

    function showAll() { all.forEach(function (e) { e.classList.add('in'); }); }
    if (reduce || !('IntersectionObserver' in window)) { showAll(); return; }

    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (e.isIntersecting) { e.target.classList.add('in'); io.unobserve(e.target); }
      });
    }, { threshold: 0, rootMargin: '0px 0px -10% 0px' });
    all.forEach(function (e) { io.observe(e); });

    // Hard failsafe: content can never be trapped hidden, whatever the observer does.
    window.addEventListener('load', function () { setTimeout(showAll, 1800); });
  })();

  /* ====================================================================
     Card tilt — extreme, with a pointer-tracked glow inside the card.
     No cursor-followers, no magnetic buttons: the effect lives in the card.
     ==================================================================== */
  if (fine && !reduce && !isRead) {
    var cards = document.querySelectorAll('.card, .explore-card, .post-card, .related-card, .feature-post');
    Array.prototype.forEach.call(cards, function (card) {
      card.addEventListener('mousemove', function (e) {
        var r = card.getBoundingClientRect();
        var px = (e.clientX - r.left) / r.width;
        var py = (e.clientY - r.top) / r.height;
        card.style.setProperty('--mx', (px * 100) + '%');
        card.style.setProperty('--my', (py * 100) + '%');
        card.style.transform = 'perspective(1000px) rotateX(' + ((py - 0.5) * -18) +
          'deg) rotateY(' + ((px - 0.5) * 18) + 'deg) scale(1.04)';
      });
      card.addEventListener('mouseleave', function () { card.style.transform = ''; });
    });
  }

  /* Booted cleanly all the way to the end — stand down the `.js` safety net set
     in base.html. If anything above had thrown, this line is never reached and
     the timer strips `.js`, making every hidden element visible. */
  clearTimeout(window.__cinemaBoot);
})();
